version: "3"
services:
  hummingbot:
    image: hummingbot/hummingbot:latest
    container_name: hummingbot-instance
    volumes:
      - ./conf:/conf
      - ./logs:/logs
    restart: always
    entrypoint: >
      /bin/bash -c "hummingbot run"
